[pytest]
DJANGO_SETTINGS_MODULE = test_redis_admin.settings
pythonpath = .
testpaths = tests
python_files = test_*.py
addopts =
    --strict-config
    --strict-markers
    -ra
    --cov=redis_admin
    --cov-report=term-missing
