"""Django settings for the test and demo project.

The test suite, the documentation build and the type checkers import this
module directly. `settings_demo` layers the demo-only Redis configuration on
top of it.
"""

from __future__ import annotations

import pathlib
import typing

BASE_DIR: pathlib.Path = pathlib.Path(__file__).resolve().parent

# Demo project only. Never reuse this key in a real deployment.
SECRET_KEY: str = 'django-redis-admin-demo-key-not-a-secret'

DEBUG: bool = True

ALLOWED_HOSTS: list[str] = ['*']

INSTALLED_APPS: list[str] = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'redis_admin',
]

MIDDLEWARE: list[str] = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF: str = 'test_redis_admin.urls'

TEMPLATES: list[dict[str, typing.Any]] = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION: str = 'test_redis_admin.wsgi.application'

# The SQLite file is generated by `python -m test_redis_admin.demo` and is
# ignored by git.
DATABASES: dict[str, dict[str, typing.Any]] = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

AUTH_PASSWORD_VALIDATORS: list[dict[str, str]] = [
    {
        'NAME': (
            'django.contrib.auth.password_validation.'
            'UserAttributeSimilarityValidator'
        ),
    },
    {
        'NAME': (
            'django.contrib.auth.password_validation.MinimumLengthValidator'
        ),
    },
    {
        'NAME': (
            'django.contrib.auth.password_validation.CommonPasswordValidator'
        ),
    },
    {
        'NAME': (
            'django.contrib.auth.password_validation.NumericPasswordValidator'
        ),
    },
]

LANGUAGE_CODE: str = 'en-us'

TIME_ZONE: str = 'UTC'

USE_I18N: bool = True

USE_TZ: bool = True

STATIC_URL: str = 'static/'

DEFAULT_AUTO_FIELD: str = 'django.db.models.BigAutoField'
